config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
=======
  resources :albums do
    resources :photos do
      collection do
        post 'multiple'
      end
    end
  end

  root 'albums#index'

>>>>>>> Albums & Photos Website, also Included the test cases

end

app/models/album.rb
class Album < ActiveRecord::Base
<<<<<<< HEAD
  has_many :photos
end
=======

  has_many :photos, dependent: :destroy

  validates :name, presence: true
  paginates_per 10

end


>>>>>>> Albums & Photos Website, also Included the test cases

app/models/photo.rb
<<<<<<< HEAD
class Photo < ActiveRecord::Base
  belongs_to :album
=======
class PhotoURLValidator < ActiveModel::Validator
  def validate(record)
    if record.url.present? && record.url =~ /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/
      last_chunk = record.url.split('.').last.downcase
      if !last_chunk.include?("jpg") && !last_chunk.include?("jpeg")
        record.errors[:url] << "must end with the string .jpeg or .jpg"
      end
    else
      record.errors[:url] << "must be present"
    end
  end
end

class PhotosLengthValidator < ActiveModel::Validator
  def validate(record)
    if Photo.where(album_id: record.album_id).count > 59
      record.errors[:photo] << "No more than 60 photos allowed in one album"
    end
  end
end

class Photo < ActiveRecord::Base

  belongs_to :album

  validates :album_id, :name, :url, presence: true
  validates_with PhotoURLValidator
  validates_with PhotosLengthValidator

  after_save :create_average_time

  def create_average_time
    time = 0
    self.album.photos.each do |photo|
      time = time + photo.taken_at.to_i
    end
    average_time = time/self.album.photos.length
    self.album.update_attribute(:average_date, Time.at(average_time))
  end

>>>>>>> Albums & Photos Website, also Included the test cases
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  protect_from_forgery with: :null_session

  def index
    @albums = Album.page params[:page]
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.includes(:photos).find(params[:id])
  end

  def show
    @album = Album.includes(:photos).where(id: params[:id]).first
    if @album.present?
      render template: "albums/show"
    else
      @message = 'Album not found'
      render template: "albums/notice", status: 404
    end
  end

  def create
    @album = Album.new(album_params)
    if @album.save!
      @message = "Album created"
      respond_to do |format|
        format.html { redirect_to album_path(@album.id), notice: @message }
        format.json { render template: "albums/show", notice: @message }
      end
    else
      @message = @album.errors
      respond_to do |format|
        format.html { render :new }
        format.json { render template: "albums/notice", status: 400 }
      end
    end
  end

  def update
    @album = Album.includes(:photos).find(params[:id])
    if @album.update(album_params)
      @message = "Album updated"
      respond_to do |format|
        format.html { redirect_to album_path(@album.id), notice: @message }
        format.json { render template: "albums/show", notice: @message }
      end
    else
      @message = @album.errors
      respond_to do |format|
        format.html { render :edit }
        format.json { render template: "albums/notice", status: 400 }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      respond_to do |format|
        format.html { redirect_to albums_path, notice: "Album deleted" }
        format.json {
          @message = "Album deleted"
          render template: "albums/notice"
        }
      end
    else
      respond_to do |format|
        format.html { redirect_to albums_path, notice: "Error deleting album" }
        format.json {
          @message = @album.errors
          render template: "albums/notice", status: 400
        }
      end
    end
  end

  def notice
    
  end

  private

  def album_params
    params.require(:album).permit(:name, :position)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  protect_from_forgery with: :null_session

  before_action :get_album

  def index
    redirect_to album_path(@album.id)
  end

  def show
    @photo = Photo.where(id: params[:id]).where(album_id: params[:album_id]).first
    if @photo.present?
      render template: "photos/show"
    else
      @message = 'Photo not found'
      render template: "albums/notice", status: 404
    end
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.where(id: params[:id]).where(album_id: params[:album_id]).first
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      @message = "Photo created"
      respond_to do |format|
        format.html { redirect_to album_path(@photo.album_id), notice: @message }
        format.json { render template: "albums/show", notice: @message }
      end
    else
      @message = @photo.errors
      respond_to do |format|
        format.html { render :new }
        format.json { render template: "albums/notice", status: 400 }
      end
    end
  end

  def multiple
    count = 0
    params[:photos].each do |photo|
      photo = photo[1]
      @photo = Photo.create(
        album_id: params[:album_id].present? ? params[:album_id] : '',
        name: photo[:name].present? ? photo[:name] : '',
        description: photo[:description].present? ? photo[:description] : '',
        url: photo[:url].present? ? photo[:url] : '',
        taken_at: photo[:taken_at].present? ? photo[:taken_at] : ''
      )
      if @photo.save
        count = count + 1
      end
    end
    @message = count.to_s+' photos created'
    respond_to do |format|
      format.html { redirect_to album_path(params[:album_id]), notice: @message }
      format.json { render template: "albums/notice" }
    end
  end

  def update
    @photo = Photo.where(id: params[:id]).where(album_id: params[:album_id]).first
    if @photo.update(photo_params)
      @message = "Photo updated"
      respond_to do |format|
        format.html { redirect_to album_path(@photo.album_id), notice: @message }
        format.json { render template: "photos/show" }
      end
    else
      @message = @photo.errors
      respond_to do |format|
        format.html { render :edit }
        format.json { render template: "albums/notice", status: 400 }
      end
    end
  end

  def destroy
    @photo = Photo.where(id: params[:id]).where(album_id: params[:album_id]).first
    if @photo.destroy
      @message = "Photo deleted"
      respond_to do |format|
        format.html { redirect_to album_path(@photo.album_id), notice: "Photo deleted" }
        format.json { render template: "albums/notice" }
      end
    else
      respond_to do |format|
        format.html { redirect_to album_path(@photo.album_id), alert: "Error deleting photo" }
        format.json {
          @message = @photo.errors
          render template: "albums/notice", status: 400
        }
      end

    end
  end

  private

  def get_album
    @album = Album.find(params[:album_id])
  end

  def photo_params
    params.require(:photo).permit(:album_id, :name, :description, :url, :taken_at)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>Edit album</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= render 'form' %>
  </div>
</div>

app/views/albums/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>Albums</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <% if @albums.size > 0 %>
      <table class="table">
        <thead>
          <tr>
            <th style="width: 70%">Name</th>
            <th style="width: 10%"># of Photos</th>
            <th style="width: 10%">Average Date</th>
            <th style="width: 10%">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @albums.each do |album| %>
            <tr>
              <td><%= link_to album.name, album_path(album.id) %></td>
              <td><%= album.photos.length %></td>
              <td><%= album.average_date %></td>
              <td>
                <%= link_to "Edit", edit_album_path(album.id) %>
                <%= link_to "Delete", album_path(album.id), method: :delete, "data-confirm": "Are you sure?" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <%= paginate @albums %>
      </div>
    <% else %>
      <p>No albums</p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= link_to "Create album", new_album_path, class: 'btn btn-large btn-primary' %>
  </div>
</div>

app/views/albums/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>New album</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="">
    <%= render 'form' %>
  </div>
</div>

app/views/albums/notice.html.erb
Not Found!

app/views/albums/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1><%= @album.name %></h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <p>Contains <%= @album.photos.length %> photos.</p>
    <% @album.photos.each do |photo| %>
      <div class="media">
        <div class="media-left media-middle">
          <img class="media-object" src="<%= photo.url %>" width="50" height="50" alt="<%= photo.name %>">
        </div>
        <div class="media-body">
          <%= link_to "&times;".html_safe, album_photo_path(@album.id, photo.id), method: :delete, class: 'btn btn-large', style: 'float: right', "data-confirm": "Are you sure?" %>
          <h4 class="media-heading"><%= link_to photo.name, album_photo_path(@album.id, photo.id) %></h4>
          <h6>Taken at: <%= photo.taken_at %></h6>
          <p><%= photo.description %></p>

        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>

<% if @album.photos.length < 60 %>
  <div class="row">
    <div class="col-xs-12">
      <%= link_to "Add photo", new_album_photo_path(@album.id), class: 'btn btn-large btn-primary' %>      
    </div>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
  <div class="container" style="padding-top: 20px;">
    <div class="row">
      <div class="col-xs-12">
        <% flash.each do |type, message| %>
          <div class="alert <%= bootstrap_class_for(type) %> fade in">
            <button class="close" data-dismiss="alert">×</button>
            <%= message %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForeverChallenge</title>
<<<<<<< HEAD
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

=======
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', media: 'all' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/flash_messages", flash: flash %>
  <div class="container" style="padding-top: 40px; padding-bottom: 40px;">
    <%= yield %>
  </div>
>>>>>>> Albums & Photos Website, also Included the test cases
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for [@album, @photo] do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :album_id, value: @album.id %>
    <div id="div_add">
      <%= render partial: "sub_form", locals: {'f': f} %>  
    </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br/>

<% unless @photo.id %>
  <button class="btn btn-large btn-primary" id="add_button"> Add more photos </button>
<% end %>

app/views/photos/_sub_form.html.erb
<div style="float:left" class="section">
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<div class="field">
  <%= f.label :url %><br>
  <%= f.text_field :url %>
</div>
<div class="field">
  <%= f.label :taken_at %><br>
  <%= f.date_field :taken_at %>
</div>
</div>

app/views/photos/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>Edit photo</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= render 'form' %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>New photo</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= render 'form' %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1><%= @photo.name %></h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left media-middle">
        <img class="media-object" src="<%= @photo.url %>" width="50" height="50" alt="<%= @photo.name %>">
      </div>
      <div class="media-body">
        <h6>Taken at: <%= @photo.taken_at %></h6>
        <p><%= @photo.description %></p>
      </div>
    </div>
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= link_to "Edit", edit_album_photo_path(@photo.album_id, @photo.id), class: 'btn btn-large btn-primary' %>
    <%= link_to "Delete", album_photo_path(@photo.album_id, @photo.id), method: :delete, class: 'btn btn-large btn-danger' %>
  </div>
</div>

<%= link_to "Back to Albums", "/" %>